# Generated by Django 5.2 on 2026-04-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="boundary_points",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Boundary Points"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="gps_accuracy_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="GPS Accuracy (m)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="gps_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="GPS Latitude",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="gps_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="GPS Longitude",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="last_mapped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Mapped At"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapped_area_hectares",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Mapped Area (hectares)",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapping_method",
            field=models.CharField(
                choices=[
                    ("manual_pin", "Manual Pin"),
                    ("walk_boundary", "Walk Boundary"),
                    ("draw_boundary", "Draw Boundary"),
                ],
                default="manual_pin",
                max_length=20,
                verbose_name="Mapping Method",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="verification_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Verification Notes"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("needs_review", "Needs Review"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Verification Status",
            ),
        ),
    ]
