# Generated by Django 5.2 on 2026-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_farm_boundary_points_farm_gps_accuracy_meters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="boundary_point_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Boundary Point Count"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapping_duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Mapping Duration (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapping_finished_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mapping Finished At"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapping_session_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="idle",
                max_length=20,
                verbose_name="Mapping Session Status",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="mapping_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mapping Started At"
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="path_distance_meters",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Path Distance (meters)",
            ),
        ),
    ]
