# Generated by Django 5.2 on 2026-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_farm_boundary_point_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_lead_farmer",
            field=models.BooleanField(default=False, verbose_name="Is Lead Farmer"),
        ),
    ]
