# Generated by Django 5.2 on 2025-07-26 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_phone', models.CharField(max_length=20)),
                ('farmer_location', models.CharField(blank=True, max_length=200)),
                ('message_type', models.CharField(choices=[('inquiry', 'General Inquiry'), ('complaint', 'Complaint'), ('request', 'Request for Help'), ('report', 'Field Report'), ('image_analysis', 'Image Analysis Request')], default='inquiry', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='farmer_images/')),
                ('image_analysis_requested', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('reply_type', models.CharField(choices=[('answer', 'Answer'), ('advice', 'Agricultural Advice'), ('referral', 'Referral'), ('follow_up', 'Follow-up Question')], default='answer', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sms_reference', models.CharField(blank=True, max_length=50)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gova_pp.farmermessage')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_text', models.TextField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('detected_issues', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('openai_model_used', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('primary_category', models.CharField(choices=[('crop_disease', 'Crop Disease'), ('pest_infestation', 'Pest Infestation'), ('nutrient_deficiency', 'Nutrient Deficiency'), ('soil_condition', 'Soil Condition'), ('plant_health', 'Plant Health'), ('harvest_readiness', 'Harvest Readiness'), ('other', 'Other')], default='other', max_length=20)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='gova_pp.farmermessage')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
