# Generated by Django 5.2 on 2025-07-26 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gova_pp', '0002_alert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark as urgent for immediate attention'),
        ),
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, help_text='Region/District/Village affected', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('weather', 'Weather Change'), ('pest', 'Pest Infestation'), ('flood', 'Flood Risk'), ('market', 'Market Price Change'), ('disease', 'Livestock Disease'), ('advisory', 'General Advisory'), ('emergency', 'Emergency Alert'), ('general', 'General Information')], default='general', max_length=20),
        ),
    ]
