# Generated by Django 4.2.23 on 2025-11-07 04:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gova_pp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gova_pp', '0003_alter_alert_options_rename_message_alert_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=gova_pp.models.chat_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'mp3', 'wav', 'ogg', 'mp4', 'mov', 'avi', 'txt', 'csv', 'json'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='document', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encryption_key', models.TextField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Media duration in seconds', null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_chat_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Media',
                'verbose_name_plural': 'Chat Media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
