# Generated by Django 4.2.23 on 2025-11-07 04:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gova_pp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gova_pp', '0004_chatmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmedia',
            name='encryption_key',
            field=models.TextField(blank=True, help_text='Encryption key (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the file should expire (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='file',
            field=models.FileField(upload_to=gova_pp.models.chat_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'mov', 'avi', 'webm', 'mkv', 'txt', 'csv', 'json', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='file_name',
            field=models.CharField(help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='is_encrypted',
            field=models.BooleanField(default=False, help_text='Whether the file is encrypted'),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='message_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='document', help_text='Type of media file', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='mime_type',
            field=models.CharField(help_text='File MIME type', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded'),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_chat_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
