# Generated by Django 4.2.23 on 2025-12-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gova_pp', '0005_alter_chatmedia_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for image files', null=True, upload_to='chat_media/thumbnails/'),
        ),
    ]
