# Generated by Django 5.2 on 2026-03-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gova_pp", "0006_chatmedia_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="governmentreply",
            name="reply_type",
            field=models.CharField(
                choices=[
                    ("answer", "Answer"),
                    ("advice", "Agricultural Advice"),
                    ("referral", "Referral"),
                    ("follow_up", "Follow-up Question"),
                    ("farmer_reply", "Farmer Reply"),
                ],
                default="answer",
                max_length=20,
            ),
        ),
    ]
