# Generated by Django 4.2.23 on 2025-11-14 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcopGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text='Name of the cooperative group', max_length=255, unique=True)),
                ('primary_crop', models.CharField(help_text='Primary crop for this group', max_length=100)),
                ('location', models.CharField(help_text='Geographic location of the group', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the group is currently active')),
                ('founder', models.ForeignKey(help_text='User who created this group (becomes Lead Farmer)', on_delete=django.db.models.deletion.PROTECT, related_name='founded_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ecop Group',
                'verbose_name_plural': 'Ecop Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcopCommitment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(help_text='Type of crop being committed', max_length=100)),
                ('total_volume', models.DecimalField(decimal_places=2, help_text='Total volume in kg', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the commitment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price per kg', max_digits=10, null=True)),
                ('buyer', models.ForeignKey(blank=True, help_text='Buyer who matched with this commitment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecop_purchases', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group making this commitment', on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='ecop.ecopgroup')),
            ],
            options={
                'verbose_name': 'Ecop Commitment',
                'verbose_name_plural': 'Ecop Commitments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcopJoinRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the join request', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True, help_text='Optional note from the group founder', null=True)),
                ('farmer', models.ForeignKey(help_text='The farmer requesting to join the group', on_delete=django.db.models.deletion.CASCADE, related_name='ecop_join_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group being requested to join', on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='ecop.ecopgroup')),
            ],
            options={
                'verbose_name': 'Ecop Join Request',
                'verbose_name_plural': 'Ecop Join Requests',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'farmer')},
            },
        ),
        migrations.CreateModel(
            name='EcopGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the membership is active')),
                ('group', models.ForeignKey(help_text='The group this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ecop.ecopgroup')),
                ('user', models.ForeignKey(help_text='The user who is a member of the group', on_delete=django.db.models.deletion.CASCADE, related_name='ecop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ecop Group Member',
                'verbose_name_plural': 'Ecop Group Members',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EcopFarmerCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume in kg committed by this farmer', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether the farmer has been paid')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was processed', null=True)),
                ('commitment', models.ForeignKey(help_text='The parent group commitment', on_delete=django.db.models.deletion.CASCADE, related_name='farmer_commitments', to='ecop.ecopcommitment')),
                ('farmer', models.ForeignKey(help_text='The farmer making this commitment', on_delete=django.db.models.deletion.CASCADE, related_name='my_ecop_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ecop Farmer Commitment',
                'verbose_name_plural': 'Ecop Farmer Commitments',
                'unique_together': {('commitment', 'farmer')},
            },
        ),
    ]
