# Generated by Django 5.2 on 2026-04-02 09:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ecopcommitment",
            name="cancellation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ecopcommitment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecopcommitment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the commitment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_ecop_commitments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ecopcommitment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecopcommitment",
            name="target_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Target price per kg",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the farmer commitment was cancelled",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="committed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When the farmer commitment was recorded",
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the farmer commitment was confirmed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount to be paid to the farmer",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Payment reference or transaction ID",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="ecopfarmercommitment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                help_text="Status of the farmer's commitment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ecopgroupmember",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ecopjoinrequest",
            name="message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional note from the farmer requesting to join",
            ),
        ),
        migrations.AlterField(
            model_name="ecopcommitment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("confirmed", "Confirmed"),
                    ("matched", "Matched"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                help_text="Current status of the commitment",
                max_length=20,
            ),
        ),
    ]
