# Generated by Django 5.2 on 2026-04-02 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecop", "0002_ecopcommitment_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecopjoinrequest",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
