# Generated by Django 6.0.5 on 2026-09-25 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('experience', 'Farming experience'), ('question', 'Question'), ('advice', 'Tip / advice')], default='experience', max_length=20, verbose_name='Type')),
                ('crop', models.CharField(help_text='e.g. Maize, Beans, Tomato', max_length=100, verbose_name='Crop')),
                ('seed_variety', models.CharField(blank=True, help_text='e.g. Zamseed 606, H614', max_length=120, verbose_name='Seed / variety')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Details')),
                ('region', models.CharField(blank=True, max_length=60, verbose_name='Region')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='community/discussions/', verbose_name='Photo')),
                ('reply_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Hide from listings without deleting (e.g. spam).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Reply')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_replies', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.discussion')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['crop'], name='community_d_crop_a69e99_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['-created_at'], name='community_d_created_66cb77_idx'),
        ),
    ]
