# Generated by Django 6.0.5 on 2026-09-23 05:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstockitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='shopstockitem',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='shopstockitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='composition',
            field=models.CharField(blank=True, help_text='NPK ratio for fertilizer (e.g. 18-46-0) or active ingredient and strength for pesticides.', max_length=255),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='germination_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='maturity_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='registration_authority',
            field=models.CharField(blank=True, choices=[('tfra', 'TFRA (fertilizers)'), ('tphpa', 'TPHPA / former TPRI (pesticides)'), ('tosci', 'TOSCI (seeds)'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='registration_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='safety_precautions',
            field=models.TextField(blank=True, help_text='Protective equipment, re-entry and pre-harvest intervals.'),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='seed_variety',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='shelf_life_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='target_crops',
            field=models.JSONField(blank=True, default=list, help_text='List of crop names, e.g. ["Maize", "Beans"].'),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='toxicity_class',
            field=models.CharField(blank=True, choices=[('Ia', 'Ia: Extremely hazardous'), ('Ib', 'Ib: Highly hazardous'), ('II', 'II: Moderately hazardous'), ('III', 'III: Slightly hazardous'), ('U', 'U: Unlikely to present acute hazard')], max_length=4),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='Application rate and timing.'),
        ),
    ]
