# Generated by Django 6.0.5 on 2026-09-23 08:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_product_details_batch_expiry'),
        ('operations', '0006_inputseller_location_and_kikapu_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('pos', 'Shop counter (POS)'), ('kikapu', 'Kikapu WhatsApp order')], default='pos', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank', 'Bank / card'), ('credit', 'Credit'), ('on_delivery', 'Paid on delivery')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('opening', 'Opening stock'), ('sale', 'Sale'), ('restock', 'Received from order'), ('adjustment', 'Manual adjustment'), ('farmer_order', 'Reserved for farmer order'), ('order_cancelled', 'Farmer order cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='FarmerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('kikapu', 'Kikapu WhatsApp')], default='kikapu', max_length=20)),
                ('external_order_id', models.CharField(help_text="The caller's order id, e.g. Kikapu's KP-INP-00482.", max_length=64)),
                ('status', models.CharField(choices=[('pending', 'New'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('farmer_name', models.CharField(max_length=120)),
                ('farmer_phone', models.CharField(max_length=30)),
                ('delivery_region', models.CharField(blank=True, max_length=60)),
                ('delivery_notes', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('shop_note', models.CharField(blank=True, help_text='Latest message for the farmer, sent with status updates.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_orders', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_order', to='inputs.sale')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_orders', to='operations.inputseller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inputs.farmerorder')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_order_items', to='inputs.shopstockitem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='farmerorder',
            constraint=models.UniqueConstraint(fields=('channel', 'external_order_id'), name='unique_external_farmer_order'),
        ),
    ]
