# Generated by Django 5.2.17 on 2026-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_farmer_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleproduct',
            name='soil_type',
            field=models.JSONField(blank=True, default=list, help_text='Soil types this suits, e.g. ["clay_loam", "well_drained"]. Required for seeds and seedlings.'),
        ),
        migrations.AddField(
            model_name='wholesaleproduct',
            name='suitable_regions',
            field=models.JSONField(blank=True, default=list, help_text='Tanzania regions this performs well in. Required for seeds and seedlings.'),
        ),
    ]
