# Generated by Django 4.2.23 on 2025-10-20 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('kikapu_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created_partial', 'Created Partial Profile'), ('already_exists', 'User Already Exists'), ('error', 'Error During Sync')], max_length=20)),
                ('inferred_location', models.CharField(blank=True, max_length=200)),
                ('predicted_crops', models.JSONField(default=list)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('farm_name', models.CharField(blank=True, max_length=200)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Operation',
                'verbose_name_plural': 'Sync Operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage_before', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_percentage_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fields_updated', models.JSONField(default=list)),
                ('missing_fields_before', models.JSONField(default=list)),
                ('missing_fields_after', models.JSONField(default=list)),
                ('time_to_complete', models.DurationField(blank=True, null=True)),
                ('updated_data', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('sync_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='authentication.syncoperation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Completion',
                'verbose_name_plural': 'Profile Completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('location', 'Location Prediction'), ('crops', 'Crop Prediction'), ('farm_size', 'Farm Size Prediction')], max_length=20)),
                ('predicted_value', models.JSONField()),
                ('actual_value', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('phone_prefix', models.CharField(blank=True, max_length=10)),
                ('farm_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_accuracy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Accuracy',
                'verbose_name_plural': 'Data Accuracy Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['-created_at'], name='authenticat_created_036956_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_f9fdf3_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['status'], name='authenticat_status_692328_idx'),
        ),
        migrations.AddIndex(
            model_name='profilecompletion',
            index=models.Index(fields=['-completed_at'], name='authenticat_complet_a4e1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='profilecompletion',
            index=models.Index(fields=['user'], name='authenticat_user_id_8e0f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccuracy',
            index=models.Index(fields=['prediction_type'], name='authenticat_predict_dc2722_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccuracy',
            index=models.Index(fields=['is_correct'], name='authenticat_is_corr_00cf76_idx'),
        ),
    ]
