# Generated by Django 6.0.5 on 2026-09-23 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inputs', '0003_farmer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Who holds this key, e.g. Kikapu production.', max_length=100)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, help_text='First characters, to recognise the key.', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('gave_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kikapu_webhooks', to='inputs.farmerorder')),
            ],
            options={
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
