# Generated by Django 6.0.5 on 2026-09-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_inputseller_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputseller',
            name='seller_type',
            field=models.CharField(choices=[('seedling_seller', 'Seedling Seller'), ('nursery_operator', 'Nursery Operator'), ('agro_input_dealer', 'Agro-Input Dealer'), ('manufacturer', 'Input Manufacturer / Distributor')], max_length=30),
        ),
    ]
