# Generated by Django 5.2.17 on 2026-10-08 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp (via Kikapu)')], default='whatsapp', max_length=20)),
                ('phone_number', models.CharField(help_text='E.164, e.g. +255712345678', max_length=20)),
                ('farmer_name', models.CharField(blank=True, max_length=120)),
                ('language', models.CharField(default='sw', max_length=5)),
                ('region', models.CharField(blank=True, max_length=60)),
                ('last_diagnosis', models.JSONField(blank=True, null=True)),
                ('last_products', models.JSONField(blank=True, default=list)),
                ('needs_expert', models.BooleanField(default=False, help_text='The latest photo needs an extension officer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('farmer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('assistant', 'Assistant')], max_length=10)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('image', 'Photo')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, help_text='The message, or the caption sent with a photo.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assistant/photos/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('external_id', models.CharField(blank=True, help_text='WhatsApp message id, used to ignore duplicate deliveries.', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='assistant.message')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('channel', 'phone_number'), name='unique_assistant_conversation'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('conversation', 'external_id'), name='unique_assistant_external_message'),
        ),
    ]
