# Generated by Django 5.2 on 2025-08-09 09:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kichwa')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('text', 'Text'), ('audio', 'Audio'), ('animation', 'Animation')], default='video', max_length=20, verbose_name='Aina ya Maudhui')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo URL', verbose_name='URL ya Video')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='training/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'wmv'])], verbose_name='Faili la Video')),
                ('video_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds', verbose_name='Muda wa Video (sekunde)')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='training/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx'])], verbose_name='Faili la Nyaraka')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='training/audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg'])], verbose_name='Faili la Sauti')),
                ('text_content', models.TextField(blank=True, verbose_name='Maudhui ya Maandishi')),
                ('allow_download', models.BooleanField(default=True, verbose_name='Ruhusu Kupakua')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Idadi ya Maono')),
            ],
            options={
                'verbose_name': 'Somo',
                'verbose_name_plural': 'Masomo',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Shirika')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='training/organizations/', verbose_name='Nembo')),
                ('website', models.URLField(blank=True, verbose_name='Tovuti')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Barua pepe')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Namba ya simu')),
                ('address', models.TextField(blank=True, verbose_name='Anwani')),
                ('is_government', models.BooleanField(default=False, verbose_name='Shirika la Serikali')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Imethibitishwa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shirika',
                'verbose_name_plural': 'Mashirika',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Jina la Lebo')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Lebo',
                'verbose_name_plural': 'Lebo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jina la Kategoria')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class', max_length=50, verbose_name='Ikoni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='training.category', verbose_name='Kategoria Kuu')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategoria',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kichwa cha Kozi')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Kichwa Kidogo')),
                ('description', models.TextField(verbose_name='Maelezo')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Maelezo Mafupi')),
                ('instructor_name', models.CharField(blank=True, max_length=100, verbose_name='Jina la Mkufunzi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='training/courses/', verbose_name='Picha Kuu')),
                ('level', models.CharField(choices=[('beginner', 'Mwanzo'), ('intermediate', 'Kati'), ('advanced', 'Juu')], default='beginner', max_length=20, verbose_name='Kiwango')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Mahitaji ya Awali')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='Malengo ya Kujifunza')),
                ('target_audience', models.CharField(blank=True, max_length=200, verbose_name='Walengwa')),
                ('language', models.CharField(default='Swahili', max_length=20, verbose_name='Lugha')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Ina Cheti')),
                ('status', models.CharField(choices=[('draft', 'Rasimu'), ('published', 'Imechapishwa'), ('archived', 'Imehifadhiwa')], default='draft', max_length=20, verbose_name='Hali')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Inayopendekezwa')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Idadi ya Maono')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Ruhusu Maoni')),
                ('estimated_duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes', verbose_name='Muda Unaokadiriwa (dakika)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='training.category', verbose_name='Kategoria')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='training.organization', verbose_name='Shirika')),
                ('tags', models.ManyToManyField(blank=True, related_name='courses', to='training.tag', verbose_name='Lebo')),
            ],
            options={
                'verbose_name': 'Kozi',
                'verbose_name_plural': 'Kozi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kichwa')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('file', models.FileField(upload_to='training/attachments/', verbose_name='Faili')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='training.lesson', verbose_name='Somo')),
            ],
            options={
                'verbose_name': 'Kiambatisho cha Somo',
                'verbose_name_plural': 'Viambatisho vya Masomo',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kichwa')),
                ('description', models.TextField(blank=True, verbose_name='Maelezo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Mpangilio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.course', verbose_name='Kozi')),
            ],
            options={
                'verbose_name': 'Moduli',
                'verbose_name_plural': 'Moduli',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.module', verbose_name='Moduli'),
        ),
        migrations.CreateModel(
            name='OrganizationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Jina la Shirika')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Jina la Mwasiliani')),
                ('email', models.EmailField(max_length=254, verbose_name='Barua pepe')),
                ('phone', models.CharField(max_length=20, verbose_name='Namba ya simu')),
                ('course_title', models.CharField(max_length=200, verbose_name='Kichwa cha Kozi')),
                ('course_description', models.TextField(verbose_name='Maelezo ya Kozi')),
                ('materials_description', models.TextField(verbose_name='Maelezo ya Nyenzo')),
                ('sample_url', models.URLField(blank=True, verbose_name='URL ya Mfano')),
                ('message', models.TextField(blank=True, verbose_name='Ujumbe wa Ziada')),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=20, verbose_name='Hali')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Maelezo ya Msimamizi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Iliwasilishwa')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ilihaririwa')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.category', verbose_name='Kategoria')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ilihaririwa na')),
            ],
            options={
                'verbose_name': 'Maombi ya Shirika',
                'verbose_name_plural': 'Maombi ya Mashirika',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Namba ya Cheti')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Utoaji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.course', verbose_name='Kozi')),
            ],
            options={
                'verbose_name': 'Cheti',
                'verbose_name_plural': 'Vyeti',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Ukadiriaji')),
                ('review', models.TextField(blank=True, verbose_name='Maoni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='training.course', verbose_name='Kozi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Ukadiriaji wa Kozi',
                'verbose_name_plural': 'Ukadiriaji wa Kozi',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Bado Kuanza'), ('in_progress', 'Inaendelea'), ('completed', 'Imekamilika')], default='not_started', max_length=20, verbose_name='Hali')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='Sekunde Zilizotazamwa')),
                ('last_position', models.PositiveIntegerField(default=0, verbose_name='Nafasi ya Mwisho (sekunde)')),
                ('completed', models.BooleanField(default=False, verbose_name='Imekamilika')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Ilifikishwa Mwisho')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ilikamilika')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training.lesson', verbose_name='Somo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Maendeleo ya Somo',
                'verbose_name_plural': 'Maendeleo ya Masomo',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Bado Kuanza'), ('in_progress', 'Inaendelea'), ('completed', 'Imekamilika')], default='not_started', max_length=20, verbose_name='Hali')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='Asilimia ya Maendeleo')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Ilifikishwa Mwisho')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Ilianza')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ilikamilika')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='training.course', verbose_name='Kozi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to=settings.AUTH_USER_MODEL, verbose_name='Mtumiaji')),
            ],
            options={
                'verbose_name': 'Maendeleo ya Mtumiaji',
                'verbose_name_plural': 'Maendeleo ya Watumiaji',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
